version: '3.8'

services:
  webapi:
    image: warehouse-webapi:latest 
    container_name: warehouse-webapi
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5276:80"  # Map the container's port 80 to host port 5276

    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: warehouse-postgres
    environment:
      POSTGRES_DB: WarehouseDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3e23O}[T*=Zf
    ports:
      - "5433:5432"  # Map the container's port 5432 to host port 5433
